In [80]:
import pandas as pd
from datetime import datetime as dt
import numpy as np
import uuid

In [676]:
import random
random.randint(0,1000)

76

In [661]:
events = pd.DataFrame(columns=['event_url'],index=['event_id'])
event_parsipients = pd.DataFrame(columns=['contact_id','patient_id'],index=['event_id'])

In [653]:
# # The function get df and start time, create the event and reutrn url 
def create_event(df,start_time,contact_id,patient_id):
    df.at[start_time,'event']=1
    return df

def check_if_date_between(date,start,end):
    return start <= date <= end

# The function get start end and freq and return pd_data range
def get_date_range(start,end,freq):
    return pd.date_range(start=start,end=end,freq=freq)

# The function get availble_hours df and return time period dataframe
def get_availble_hours_df(availble_hours_df):
    df = pd.concat([pd.DataFrame({\
                'start_time': get_date_range(start=row['date_from'],end=row["date_to"],freq='20min')})\
                for index,row in availble_hours_df.iterrows()])
    df.set_index("start_time",inplace=True)
    return df

# The function get contacts data frame and patient id and return all contacts belong to the patient
def get_all_contacts_of_patient(df,patient_id):
    return df.loc[df.contact_patient == patient_id].index

# The function get df and return df with all datetime columns
def convert_columns_to_date_time(df):
    for col in df:
        df[col] = pd.to_datetime(df[col])
    return df

# The function iterate over all contacts hours of contact and return true if time availble 
def check_contact_hours(df,avaible_time,contact_id):
    for index,row in df.loc[1,['availble_contact_hours']].itertuples():
        if(row[0] <= avaible_time ,row[1]):
            return True
    return False

# The function get df and return availble times if event is none
def get_all_availble_times(df):
    return df.loc[a_df_hours.event.isna()]

# The function get df and return the minimum date availble
def get_min_availble_time(df):
    return df.loc[df.event.isna()].index.min()

In [655]:
# Read table with availble hours
df = pd.read_csv('./available_meting_timestamp.csv',parse_dates=["date_from","date_to"]).drop(columns='Unnamed: 2')

# Create availble hours dataframe with freq of 20 minutes from date_from to date_to
df_a_hours = get_availble_hours_df(df)

# Reset event column with non values
df_a_hours["event"] = np.nan

In [656]:
# Read patients table
patients_df = pd.read_csv('./patients.csv',index_col='patient_id')

# Read contacts table
contacts_df = pd.read_csv('./contacts.csv',index_col='contact_id')

# Read contacts hours table
a_contacts_hours = pd.read_csv('contacts_availble_hours.csv',index_col='contact_id')

# Convert contacts table columns to datetype
a_contacts_hours = convert_columns_to_date_time(a_contacts_hours)

# Create tuple from_date and to_date
a_contacts_hours = a_contacts_hours.assign(availble_contact_hours=list(zip(a_contacts_hours.from_date,a_contacts_hours.to_date)))

In [658]:
# Itrerate over all patients 
for patient_id,row in patients_df.iterrows():
    try:
#         Try deined contact_id
        contact_id = get_all_contacts_of_patient(contacts_df,patient_id)[0]
    except:
        print("patient_id:{} patient_name:{} no has contacts".format(patient_id,row.patient_name))
        continue
#     Get min available time
    availble_time = get_min_availble_time(df_a_hours)
    print(contact_id)
    print(availble_time)
    
#     Create event 
    df_a_hours = create_event(df_a_hours,availble_time)
    if(check_contact_hours(a_contacts_hours,availble_time,contact_id)):
        df_a_hours = create_event(df_a_hours,availble_time)
    else:
        while(not check_contact_hours(a_contacts_hours,availble_time,contact_id)):
            availble_time = get_min_availble_time(a_df_hours)
    df_a_hours = create_event(df_a_hours,availble_time)
    
    
df_a_hours.loc[df_a_hours.event ==1]

1
2022-08-14 11:20:00
3
2022-08-14 11:40:00
4
2022-08-14 12:00:00
5
2022-08-14 12:20:00
patient_id:5 patient_name:shaul no has contacts
patient_id:6 patient_name:Gidi no has contacts
patient_id:7 patient_name:avraham no has contacts
patient_id:8 patient_name:shahaf no has contacts

                     event
start_time
2022-08-14 10:00:00    1.0
2022-08-14 10:20:00    1.0
2022-08-14 10:40:00    1.0
2022-08-14 11:00:00    1.0
2022-08-14 11:20:00    1.0
2022-08-14 11:40:00    1.0
2022-08-14 12:00:00    1.0
2022-08-14 12:20:00    1.0

In [626]:

    
#     df = 
#     return df
#     print(df.loc[start_time])
#     print(type(df))
#     df =df.loc[start_time,'event'] == 1
df_a_hours = create_event(df_a_hours,availble_time)
# df = df_a_hours
# df_a_hours
# df_a_hours

                     event
start_time
2022-08-14 10:00:00    4.0
2022-08-14 10:20:00    NaN
2022-08-14 10:40:00    NaN
2022-08-14 11:00:00    NaN
2022-08-14 11:20:00    NaN
...                    ...
2022-08-20 13:40:00    NaN
2022-08-20 14:00:00    NaN
2022-08-20 14:20:00    NaN
2022-08-20 14:40:00    NaN
2022-08-20 15:00:00    NaN

[70 rows x 1 columns]

In [591]:



#     print(availble_time)
#     break
#     while(not check_contact_hours(avaible_time=))
#     print(contact_id)
# #     availble_time = get_min_availble_time(a_df_hours)
# #     while(not check_if_date_between):
# #         availble_time = get_min_availble_time(a_df_hours)
# #     df = create_event(df,availble_time)
# contact_id = patients_df['']
# patients_df.merge(contacts_df,left_on=patients_df.index,right_on='contact_patient',how='inner')
# contact_id = get_all_contacts_of_patient(contacts_df,2)[]
# contact_id

1
2022-08-14 10:00:00
True
3
2022-08-14 10:00:00
True

AttributeError: 'numpy.bool_' object has no attribute 'loc'

In [396]:
# a_contacts_hours = pd.DataFrame(columns=["from_date","to_date"],index= [1,1,2,2,3,6,1,8,1])
# a_contacts_hours.sort_index(inplace=True)
a_contacts_hours = pd.read_csv('contacts_availble_hours.csv',index_col='contact_id')
for col in a_contacts_hours.columns:
    a_contacts_hours[col] = pd.to_datetime(a_contacts_hours[col])
a_df_hours["event"] = np.nan
# for start_time in a_df_hours.index:
#     patient_id in patients_df:
contacts_df       
def check_if_date_between(date,start,end):
    return start <= date <= end

# for patient_id,row in patients_df.iterrows():
#     contact_id = patients_df[patient_id,['']]
# #     availble_time = get_min_availble_time(a_df_hours)
# #     while(not check_if_date_between):
# #         availble_time = get_min_availble_time(a_df_hours)
# #     df = create_event(df,availble_time)
# contact_id = patients_df['']

def get_all_contacts_of_patient(df,patient_id):
    return df.loc[df.contact_patient == patient_id].index

for patient_id,row in patients_df.iterrows():
    contact_id = get_all_contacts_of_patient(contacts_df,patient_id)
    availble_time = get_min_availble_time(a_df_hours)
#     while(not check_if_date_between(availble_time,)):
        
get_min_availble_time(a_df_hours)

Timestamp('2022-08-14 10:00:00')

In [498]:
d = a_contacts_hours
d['a'] = d['from_date']
d['b'] = d['to_date']
# d
# d['D'] = d[['a','b']].apply(tuple, axis=1)
# my_df = d
d = d.assign(d=list(zip(d.a,d.b)))
# for col in d.columns:
#     d[col] = pd.to_datetime(d[col])

pandas._libs.tslibs.timestamps.Timestamp

In [475]:
# df = pd.to_datetime(a_contacts_hours.from_date)
# for col in a_contacts_hours.columns:
#     a_contacts_hours[col] = pd.to_datetime(a_contacts_hours[col])
#     

# a_contacts_hours.info()
# df.GregDate = pd.to_datetime(a)
# a_contacts_hours.availble_contact_hours =a_contacts_hours.availble_contact_hours.apply(lambda x: pd.to_datetime(x[0]))
a_contacts_hours.loc[1].values

array([['2022-08-14T10:00:00.000000000', '2022-08-14T12:00:00.000000000'],
       ['2022-08-15T11:00:00.000000000', '2022-08-15T12:00:00.000000000']],
      dtype='datetime64[ns]')

In [533]:
# Get contantcs_hours_table
a_contacts_hours = pd.read_csv('contacts_availble_hours.csv',index_col='contact_id')

# Convert columns to datetime
for col in a_contacts_hours.columns:
    a_contacts_hours[col] = pd.to_datetime(a_contacts_hours[col])

# Create tuple of from_date to_date
a_contacts_hours = a_contacts_hours.assign(availble_contact_hours=list(zip(a_contacts_hours.from_date,a_contacts_hours.to_date)))

# The function iterate over all contacts hours of contact and return true if time availble 
def check_contact_hours(df,avaible_time,contact_id):
    for index,row in df.loc[1,['availble_contact_hours']].itertuples():
        if(row[0] <= avaible_time ,row[1]):
            return True
    return False
    
check_contact_hours(a_contacts_hours,1)
# df = a_contacts_hours
# for index,row in df.loc[1,['availble_contact_hours']].itertuples():
#     print(row[0] <= get_min_availble_time(a_df_hours) ,row[1])

True

In [501]:

# print(a_contacts_hours)
# Convert tuple to datetime
# a_contacts_hours.availble_contact_hours =a_contacts_hours.availble_contact_hours.apply(lambda x: pd.to_datetime(x[0]))
a_contacts_hours
# a_contacts_hours['availble_contact_hours'] = a_contacts_hours[['from_date','to_date']].apply(tuple, axis=1)
# a_contacts_hours['availble_contact_hours'] = tuple(a_contacts_hours['availble_contact_hours'].values.tolist())
# [tuple(x) for x in a_contacts_hours[['from_date','to_date']].values.tolist()]
# result = tuple(['d', 'e', 'f'])
# a_contacts_hours
# def check_date_between_dates(start,end,date):
#     return start <= date <= end

# def check_contact_hours(df,contact_id):
#     for index,tuple in enumerate(df.loc[contact_id,['availble_contact_hours']]):
#         print(type(tuple[0]))
# #         print(tuple[0] <= get_min_availble_time(a_df_hours) <= tuple[1])
# check_contact_hours(a_contacts_hours,1)

,from_date,to_date,availble_contact_hours
contact_id,,,
1,2022-08-14 10:00:00,2022-08-14 12:00:00,"(2022-08-14 10:00:00, 2022-08-14 12:00:00)"
2,2022-08-15 11:00:00,2022-08-15 12:00:00,"(2022-08-15 11:00:00, 2022-08-15 12:00:00)"
1,2022-08-15 11:00:00,2022-08-15 12:00:00,"(2022-08-15 11:00:00, 2022-08-15 12:00:00)"
3,2022-08-17 11:00:00,2022-08-17 12:00:00,"(2022-08-17 11:00:00, 2022-08-17 12:00:00)"
2,2022-08-18 11:00:00,2022-08-18 12:00:00,"(2022-08-18 11:00:00, 2022-08-18 12:00:00)"
2,2022-08-19 11:00:00,2022-08-19 12:00:00,"(2022-08-19 11:00:00, 2022-08-19 12:00:00)"
4,2022-08-20 11:00:00,2022-08-20 12:00:00,"(2022-08-20 11:00:00, 2022-08-20 12:00:00)"
5,2022-08-17 11:00:00,2022-08-17 12:00:00,"(2022-08-17 11:00:00, 2022-08-17 12:00:00)"
7,2022-08-18 11:00:00,2022-08-18 12:00:00,"(2022-08-18 11:00:00, 2022-08-18 12:00:00)"

In [461]:
# def check_contact_hours(df,contact_id):
#     for row in df.loc[contact_id,['availble_contact_hours']]:
#         print(row.from_date <= get_min_availble_time(a_df_hours) ,row.to_date)
# check_contact_hours(a_contacts_hours,1)

# for row in a_contacts_hours.itertuples():
#     print(tuple[0] <= get_min_availble_time(a_df_hours) <= tuple[1])
#     print(row.from_date)
#     print(type(row.from_date))
# for row in a_contacts_hours.loc[1,['availble_contact_hours']].itertuples():
#     print(row.)
a_contacts_hours

                     from_date             to_date availble_contact_hours
contact_id
1          2022-08-14 10:00:00 2022-08-14 12:00:00    2022-08-14 10:00:00
2          2022-08-15 11:00:00 2022-08-15 12:00:00    2022-08-15 11:00:00
1          2022-08-15 11:00:00 2022-08-15 12:00:00    2022-08-15 11:00:00
3          2022-08-17 11:00:00 2022-08-17 12:00:00    2022-08-17 11:00:00
2          2022-08-18 11:00:00 2022-08-18 12:00:00    2022-08-18 11:00:00
2          2022-08-19 11:00:00 2022-08-19 12:00:00    2022-08-19 11:00:00
4          2022-08-20 11:00:00 2022-08-20 12:00:00    2022-08-20 11:00:00
5          2022-08-17 11:00:00 2022-08-17 12:00:00    2022-08-17 11:00:00
7          2022-08-18 11:00:00 2022-08-18 12:00:00    2022-08-18 11:00:00

In [403]:

a_df_hours["event"] = np.nan

get_min_availble_time(a_df_hours)
# # a_df_hours.loc[a_df_hours.event.isna()].ind
# d = a_df_hours.loc[a_df_hours.event.isna()].index.min()
a_contacts_hours['availble_contact_hours'] = list(zip(a_contacts_hours.from_date, a_contacts_hours.to_date))
# a_contacts_hours['availble_contact_hours'] =pd.to_datetime()
# for col in a_contacts_hours.columns:
#     a_contacts_hours[col] = pd.to_datetime(a_contacts_hours[col])
# def iterate_dates_serias(df):
#     for index,tuple in enumerate(df.):
#         element_one = tuple[0]
#         element_two = tuple[1]
#         print(element_one, element_two)

# Input: contact_}
# Output:
def check_date_between_dates(start,end,date):
    return start <= date <= end

def check_contact_hours(df,contact_id):
    for index,tuple in enumerate(df.loc[contact_id,['availble_contact_hours']]):
        print(tuple[0] <= get_min_availble_time(a_df_hours) <= tuple[1])
check_contact_hours(a_contacts_hours,1)

# for index,tuple in enumerate(d.new_col):
#         from_date = tuple[0]
#         to_date = tuple[1]
#         print(element_one)
#         print(element_two)
#         print(element_one <= get_min_availble_time(a_df_hours) <= element_two)
# d

# print(get_min_availble_time(a_df_hours))
# # print(element_one)
# # print(element_two)
# element_one <= get_min_availble_time(a_df_hours) <= element_two
# #         mask = (get_min_availble_time(a_df_hours) > element_one) & (get_min_availble_time(a_df_hours) <= element_two)
# # df2 = df.loc[mask]
# # print(df2)
# # a_contacts_hours.info()

TypeError: '<=' not supported between instances of 'str' and 'Timestamp'

In [254]:
for index,row in a_contacts_hours.loc[1].iterrows():
    check_if_date_between()

                       from_date               to_date
contact_id
1            10:00:00 14/08/2022   12:00:00 14/08/2022
1            11:00:00 15/08/2022   12:00:00 16/08/2022

In [313]:
def get_all_availble_times(df):
    return df.loc[a_df_hours.event.isna()]
def get_min_availble_time(df):
    return df.loc[df.event.isna()].index.min()

# def check_availble

# # The function get df and start time, create the event and reutrn url 
def create_event(df,start_time):
    return df.loc[start_time,'event'] == 1

In [231]:
contacts_df['max_cols'] = [1,1,2,1,2,1,1,1]

In [ ]:
for patient

In [201]:

create_event(a_df_hours,'2022-08-14 10:20:00')
def get_availble_hours(df):
    return df.loc[start_time,['event'] == 1]

In [173]:
patients_df.merge(contacts_df,left_on=patients_df.index,right_on='contact_patient',how='inner')

,patient_name,patient_bad,contact_f_name,contact_l_name,contact_phone,contact_mail,contact_patient,contact_priotirty
0,tal,18,niv,b,2,nivbdbd@gmail.com,1,1
1,tal,18,tal,c,2,nivbdbd@gmail.com,1,1
2,or,27,or,d,3,nivbdbd@gmail.com,2,1
3,lipaz,3,omar,e,2,NaN,3,1
4,lipaz,3,beni,s,2,NaN,3,1
5,lipaz,3,tal,a,4,NaN,3,0
6,niv,1,gilad,w,4,NaN,4,1
7,niv,1,eden,a,3,NaN,4,1

In [177]:
# def create_event(df):
patients_df.loc[1,['patient_name']]

patient_name    tal
Name: 1, dtype: object

In [83]:
# tmin, tmax = df['date_from'].min(), df['date_from'].max()
rng = pd.date_range(start=df['date_from'],df['date_from'] , freq='20min')
df1 = pd.DataFrame({ 'Date': rng, 'Val' : np.random.randn(len(rng))})  
df1

SyntaxError: positional argument follows keyword argument (1340965803.py, line 2)

In [46]:
import pandas as pd                                            # your code
date = pd.date_range(tmin, tmax, freq="AS")    # your code

freq = 'H'                                                     # 'H' for hours, etc.
date = date + pd.Timedelta(20, unit=freq)                       # Perform the action
print(date)

DatetimeIndex([], dtype='datetime64[ns]', freq=None)